// cyclops-cs backend — sidecar for the cyclops-cs Pod.
//
// Every authenticated route runs through the standard
//
//	Trace → Log → TokenAuth → OPA → handler
//
// pipeline borrowed from r33drichards/grt:
//
//	/api/keys[/{id}]            — SPA-authenticated CRUD on per-user
//	                              service-account clients in Keycloak.
//
//	@title						Cyclops CS Backend API
//	@version					0.1
//	@description				Backend sidecar for the cyclops-cs SPA — Keycloak-authenticated key management, service proxies (k8s / svc), and namespace management. All pool operations use OSGymSandboxClaim CRs (Path B).
//	@BasePath					/
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				Keycloak access token. For /api/keys and /api/k8s the token is an interactive user JWT (azp=cyclops-cs-spa or azp=cua-cli).
package main

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"
	"time"

	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"

	"github.com/spf13/cobra"

	"cyclops-cs-backend/accountlookup"
	"cyclops-cs-backend/auth"
	"cyclops-cs-backend/billing"
	"cyclops-cs-backend/chat"
	"cyclops-cs-backend/config"
	"cyclops-cs-backend/database"
	_ "cyclops-cs-backend/docs" // generated by `swag init`
	"cyclops-cs-backend/featureflagadmin"
	"cyclops-cs-backend/githubtrust"
	"cyclops-cs-backend/handlers"
	"cyclops-cs-backend/keycloak"
	"cyclops-cs-backend/metrics"
	"cyclops-cs-backend/middlewares"
	"cyclops-cs-backend/productanalytics"
	"cyclops-cs-backend/signedurls"
	"cyclops-cs-backend/statequery"
	"cyclops-cs-backend/telemetry"
	"cyclops-cs-backend/usage"

	httpSwagger "github.com/swaggo/http-swagger/v2"
	"github.com/trycua/cloud/pkg/featureflags"
)

var configValues *config.Configuration

func withMiddlewares(handler http.Handler, chain ...auth.Middleware) http.Handler {
	for index := len(chain) - 1; index >= 0; index-- {
		handler = chain[index](handler)
	}
	return handler
}

func traceMiddleware(route string) auth.Middleware {
	return func(next http.Handler) http.Handler {
		return middlewares.TraceMiddleware(route, next)
	}
}

// withAuthenticatedMiddlewares is the chain every authenticated route runs
// through: Trace → Log → RouteContext → TokenAuth → policy.
//
// Which policy is not decided here. auth.RouteMiddleware looks the route up in
// the route → surface table in auth/policy_routes.go, so the route name passed
// to RouteContext — the same string the policy matches as input.route — is also
// what selects the policy. A route this file registers but that table does not
// name panics during route construction rather than serving traffic on a policy
// nobody chose. Plans are memoized per surface, not per route, so routes sharing
// a surface share one compiled plan.
//
// The route name is also the only place its path parameters are named:
// RouteContext reads the wildcards out of the pattern, so a route cannot be
// registered with a parameter list that disagrees with the path it serves.
//
// The policy stage ran on a bespoke middleware until it moved onto the
// composable policy library, and evaluated one route-aware module for every
// route until that module was decomposed into a shared base plus one surface
// module per group of routes. Neither move changed a verdict: the two
// middlewares were held to identical status and body across allow, deny and
// undecidable requests until the old one was deleted, and the decomposition was
// held to auth/testdata/route-authorization-table.txt.
//
// One thing the old middleware did was dropped rather than carried over: a
// per-request slog.Debug of the elapsed time and the allow/deny result. Nothing
// consumed it and nothing could have — run() installs a JSON handler at slog's
// default level, so debug records are discarded before they are written, and no
// Loki rule, dashboard, or runbook in this repo queries an "opa" line. Its
// deferred call still paid for a time.Since and two Context.Value lookups per
// request to build a record that was then thrown away.
//
// The allow/deny verdict is already observable at Info, and better:
// LogMiddleware wraps this stage and logs route, status, duration, and trace_id
// for every request, which is what the CyclopsCSBackendHighErrorRate alert
// reads through the equivalent 5xx metric. The error string is not part of
// that — PolicyMiddleware logs it at Error itself. Re-adding elapsed time per
// policy belongs on the policy library as a span, not on one middleware as an
// unreachable log line.
func withAuthenticatedMiddlewares(route string, h http.HandlerFunc, observers ...auth.Middleware) http.Handler {
	chain := []auth.Middleware{
		traceMiddleware(route),
		middlewares.LogMiddleware,
		auth.RouteContext(route),
		auth.TokenAuthMiddleware,
	}
	chain = append(chain, observers...)
	chain = append(chain, auth.RouteMiddleware(route))
	return withMiddlewares(http.HandlerFunc(h), chain...)
}

func onlyLog(route string, h http.HandlerFunc) http.Handler {
	return middlewares.TraceMiddleware(route, middlewares.LogMiddleware(http.HandlerFunc(h)))
}

func setupRouter(c handlers.Handlers) http.Handler {
	// Observe validated, owner-normalized identities without blocking requests.
	authenticated := withAuthenticatedMiddlewares
	withAuthenticatedMiddlewares := func(route string, handler http.HandlerFunc, observers ...auth.Middleware) http.Handler {
		if c.AccountLookup != nil {
			observers = append([]auth.Middleware{c.AccountLookup.Observe}, observers...)
		}
		wrapped := authenticated(route, handler, observers...)
		if route == "/api/admin/account-lookup" {
			return handlers.PrivateAccountLookup(wrapped)
		}
		return wrapped
	}
	// The namespace-ownership conjunct on /api/svc and
	// /api/namespaces/{name} asks Kubernetes a question, through a probe that
	// is a handlers method. auth cannot import handlers, so the policy names
	// the provider and this is where the name is bound to it. It must happen
	// before the first RouteMiddleware below, because that is what compiles the
	// plans that refer to it.
	auth.RegisterFactProvider(auth.NamespaceRBACFactProvider, handlers.NamespaceRBACFacts(c))
	auth.RegisterFactProvider(auth.StripeCardsFactProvider, handlers.StripeCardFacts(c))
	auth.RegisterFactProvider(auth.CurrentYearFactProvider, auth.CurrentYearFacts(time.Now))
	auth.RegisterFactProvider(auth.CurrentMonthFactProvider, auth.CurrentMonthFacts(time.Now))

	r := http.NewServeMux()
	svcQualifier := c.FleetAttributionQualification()
	loginObserver := productanalytics.LoginObserver(c.Analytics, c.AuthCfg.SPAClientID)

	r.Handle("GET /healthz", onlyLog("/healthz", c.GetHealth))
	r.Handle("GET /readyz", onlyLog("/readyz", c.GetReadiness))

	// Feature flags / per-user config. SPA-only (same auth as /api/keys).
	r.Handle("GET /api/config",
		withAuthenticatedMiddlewares("/api/config", c.GetConfig))
	r.Handle("POST /api/analytics/session",
		withAuthenticatedMiddlewares("/api/analytics/session", c.RecordAnalyticsSession))
	r.Handle("POST /api/analytics/attribution",
		withAuthenticatedMiddlewares("/api/analytics/attribution", c.RecordFleetAttribution))
	r.Handle("POST /api/analytics/payment-gate",
		withAuthenticatedMiddlewares("/api/analytics/payment-gate", c.RecordFleetPaymentGate))

	r.Handle("POST /api/chat/conversations",
		withAuthenticatedMiddlewares("/api/chat/conversations", c.CreateConversation))
	r.Handle("GET /api/chat/conversations",
		withAuthenticatedMiddlewares("/api/chat/conversations", c.ListConversations))
	r.Handle("GET /api/chat/conversations/{id}",
		withAuthenticatedMiddlewares("/api/chat/conversations/{id}", c.GetConversation))
	r.Handle("PATCH /api/chat/conversations/{id}",
		withAuthenticatedMiddlewares("/api/chat/conversations/{id}", c.UpdateConversation))
	r.Handle("POST /api/chat/conversations/{id}/turns",
		withAuthenticatedMiddlewares("/api/chat/conversations/{id}/turns", c.CreateTurn))

	r.Handle("QUERY /api/state/query",
		withAuthenticatedMiddlewares("/api/state/query", c.QueryState))
	r.Handle("GET /api/usage/overview", withAuthenticatedMiddlewares("/api/usage/overview", c.GetUsageOverview))
	r.Handle("GET /api/usage/pool", withAuthenticatedMiddlewares("/api/usage/pool", c.GetUsagePoolDetail))
	r.Handle("POST /api/usage/browser-timings", withAuthenticatedMiddlewares("/api/usage/browser-timings", c.RecordUsageBrowserTimings))
	r.Handle("GET /api/admin/feature-flags", withAuthenticatedMiddlewares("/api/admin/feature-flags", c.ListFeatureFlags))
	r.Handle("POST /api/admin/account-lookup", withAuthenticatedMiddlewares("/api/admin/account-lookup", c.LookupAccount, c.AuditAccountLookupAccess))
	r.Handle("POST /api/admin/feature-flags", withAuthenticatedMiddlewares("/api/admin/feature-flags", c.CreateFeatureFlag))
	r.Handle("PUT /api/admin/feature-flags/{key}", withAuthenticatedMiddlewares("/api/admin/feature-flags/{key}", c.UpdateFeatureFlag))
	r.Handle("DELETE /api/admin/feature-flags/{key}", withAuthenticatedMiddlewares("/api/admin/feature-flags/{key}", c.DeleteFeatureFlag))

	r.Handle("POST /api/image-uploads/presign",
		withAuthenticatedMiddlewares("/api/image-uploads/presign", c.PresignImageUploads))

	// Stripe-hosted billing. Browser routes require the normal SPA JWT; the
	// webhook uses Stripe signature verification as its authentication boundary.
	r.Handle("GET /api/billing/summary",
		withAuthenticatedMiddlewares("/api/billing/summary", c.GetBillingSummary))
	r.Handle("GET /api/billing/usage",
		withAuthenticatedMiddlewares("/api/billing/usage", c.GetBillingUsage))
	r.Handle("POST /api/billing/setup-session",
		withAuthenticatedMiddlewares("/api/billing/setup-session", c.CreateBillingSetupSession))
	r.Handle("POST /api/billing/setup-session/complete",
		withAuthenticatedMiddlewares("/api/billing/setup-session/complete", c.CompleteBillingSetupSession))
	r.Handle("POST /api/billing/portal-session",
		withAuthenticatedMiddlewares("/api/billing/portal-session", c.CreateBillingPortalSession))
	r.Handle("POST /api/billing/webhook",
		onlyLog("/api/billing/webhook", c.HandleBillingWebhook))

	// Swagger UI + JSON. The schema is public API documentation, while the
	// actual endpoints remain behind their normal authentication boundaries.
	r.Handle("GET /api/swagger/", onlyLog("/api/swagger/", func(w http.ResponseWriter, r *http.Request) {
		httpSwagger.Handler(httpSwagger.URL("/api/swagger/doc.json")).ServeHTTP(w, r)
	}))

	r.Handle("POST /api/keys",
		withAuthenticatedMiddlewares("/api/keys", c.CreateKey))
	r.Handle("GET /api/keys",
		withAuthenticatedMiddlewares("/api/keys", c.ListKeys))
	r.Handle("DELETE /api/keys/{id}",
		withAuthenticatedMiddlewares("/api/keys/{id}", c.DeleteKey))

	// Namespace management — Capsule-backed per-user namespaces.
	// Uses K8s impersonation so Capsule sees the real user identity.
	r.Handle("GET /api/namespaces",
		withAuthenticatedMiddlewares("/api/namespaces", c.ListNamespaces))
	r.Handle("POST /api/namespaces",
		withAuthenticatedMiddlewares("/api/namespaces", c.CreateNamespace))
	r.Handle("GET /api/namespaces/{name}",
		withAuthenticatedMiddlewares("/api/namespaces/{name}", c.GetNamespace))
	r.Handle("DELETE /api/namespaces/{name}",
		withAuthenticatedMiddlewares("/api/namespaces/{name}", c.DeleteNamespace))

	// Per-user API keys — Keycloak service-account clients (ukey- prefix).
	r.Handle("POST /api/user-keys",
		withAuthenticatedMiddlewares("/api/user-keys", c.CreateUserKey))
	r.Handle("GET /api/user-keys",
		withAuthenticatedMiddlewares("/api/user-keys", c.ListUserKeys))
	r.Handle("DELETE /api/user-keys/{id}",
		withAuthenticatedMiddlewares("/api/user-keys/{id}", c.DeleteUserKey))

	r.Handle("GET /api/github-trust-policies",
		withAuthenticatedMiddlewares("/api/github-trust-policies", c.ListGitHubTrustPolicies))
	r.Handle("POST /api/github-trust-policies",
		withAuthenticatedMiddlewares("/api/github-trust-policies", c.CreateGitHubTrustPolicy))
	r.Handle("PATCH /api/github-trust-policies/{id}",
		withAuthenticatedMiddlewares("/api/github-trust-policies/{id}", c.UpdateGitHubTrustPolicy))
	r.Handle("DELETE /api/github-trust-policies/{id}",
		withAuthenticatedMiddlewares("/api/github-trust-policies/{id}", c.DeleteGitHubTrustPolicy))

	// Generic service proxy — reaches a K8s Service on port 80 in a
	// namespace the caller is authorized for. Authn, parameter shape and
	// namespace ownership are all the policy's: per-key and GitHub tokens by
	// their claims, everyone else by an impersonated RoleBinding probe the
	// policy reads as a fact — see auth/authz_ownership.rego.
	r.Handle("/api/signed-svc/{token}", onlyLog("/api/signed-svc/{token}", c.HandleSignedSvc))
	r.Handle("/api/signed-svc/{token}/{path...}", onlyLog("/api/signed-svc/{token}/{path...}", c.HandleSignedSvc))

	r.Handle("/api/svc/{namespace}/{service}",
		withAuthenticatedMiddlewares("/api/svc/{namespace}/{service}", c.Svc,
			loginObserver,
			productanalytics.RouteObserverWithQualification("/api/svc/{namespace}/{service}", c.Analytics, c.AuthCfg.SPAClientID, svcQualifier)))
	r.Handle("/api/svc/{namespace}/{service}/{path...}",
		withAuthenticatedMiddlewares("/api/svc/{namespace}/{service}/{path...}", c.Svc,
			loginObserver,
			productanalytics.RouteObserverWithQualification("/api/svc/{namespace}/{service}/{path...}", c.Analytics, c.AuthCfg.SPAClientID, svcQualifier)))

	r.Handle("POST /api/signed-service-urls/{namespace}",
		withAuthenticatedMiddlewares("/api/signed-service-urls/{namespace}", c.CreateSignedServiceURL))
	r.Handle("GET /api/signed-service-urls/{namespace}",
		withAuthenticatedMiddlewares("/api/signed-service-urls/{namespace}", c.ListSignedServiceURLs))
	r.Handle("DELETE /api/signed-service-urls/{namespace}/{id}",
		withAuthenticatedMiddlewares("/api/signed-service-urls/{namespace}/{id}", c.RevokeSignedServiceURL))

	// K8s API access replaces the unauthenticated /k8s-api nginx location.
	r.Handle("/api/k8s/{path...}",
		withAuthenticatedMiddlewares("/api/k8s/{path...}", c.K8s,
			loginObserver,
			productanalytics.RouteObserver("/api/k8s/{path...}", c.Analytics, c.AuthCfg.SPAClientID)))

	// Wrap the entire mux in the metrics middleware so every request
	// (including /healthz and unmatched routes) is recorded. This must be
	// the outermost layer so the status code from inner middlewares (auth,
	// OPA) is captured correctly.
	return metrics.Middleware(r)
}

var rootCmd = &cobra.Command{
	Use:           "cyclops-cs-backend",
	Short:         "cyclops-cs backend sidecar",
	SilenceUsage:  true,
	SilenceErrors: true,
	RunE:          func(_ *cobra.Command, _ []string) error { return run() },
}

func init() {
	config.RegisterFlags(rootCmd.PersistentFlags())
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		slog.Error("fatal", "err", err)
		os.Exit(1)
	}
}

func initializeTelemetry(ctx context.Context, cfg config.TelemetryConfiguration) (func(context.Context) error, error) {
	shutdown, err := telemetry.Init(ctx, telemetry.Config{
		Endpoint:         cfg.Endpoint,
		Protocol:         cfg.Protocol,
		ServiceName:      cfg.ServiceName,
		ServiceNamespace: cfg.ServiceNamespace,
		Environment:      cfg.Environment,
		ResourceAttrs:    cfg.ResourceAttrs,
	})
	if err != nil {
		slog.Warn("otel: init failed; telemetry disabled", "err", err)
		return func(context.Context) error { return nil }, err
	}
	return shutdown, nil
}

func productAnalyticsClientConfig(cfg config.ProductAnalyticsConfiguration) productanalytics.Config {
	return productanalytics.Config{
		Enabled: cfg.Enabled, Host: cfg.Host, ProjectToken: cfg.ProjectToken,
		IdentityKey: cfg.IdentityKey,
		Environment: cfg.Environment, ExcludedSubjects: cfg.ExcludedSubjects,
	}
}

func initializeFeatureFlags(ctx context.Context, environment string, credentials featureflags.AWSCredentials) error {
	err := featureflags.SetupProvider(ctx, environment, credentials)
	if err != nil {
		slog.Warn("openfeature: provider setup degraded", "err", err)
		return err
	}
	return nil
}

func newImageObjectStore(ctx context.Context, cfg config.ImageUploadConfiguration) (handlers.ImageObjectStore, error) {
	if strings.TrimSpace(cfg.Bucket) == "" {
		return nil, nil
	}
	awsCfg, err := awsconfig.LoadDefaultConfig(ctx, awsconfig.WithRegion(cfg.Region))
	if err != nil {
		return nil, fmt.Errorf("load image upload AWS config: %w", err)
	}
	return handlers.NewS3ImageObjectStore(s3.NewFromConfig(awsCfg), cfg.Bucket), nil
}

func run() error {
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, nil)))
	ctx, stopSignals := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stopSignals()
	var startupErrors error
	var telemetryErr error

	cfg, err := config.LoadConfig()
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	configValues = cfg

	analyticsClient := productanalytics.New(productAnalyticsClientConfig(cfg.ProductAnalytics))
	defer func() {
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()
		if err := analyticsClient.Shutdown(shutdownCtx); err != nil {
			slog.Warn("product analytics shutdown failed")
		}
	}()

	telemetryShutdown, telemetryErr := initializeTelemetry(ctx, cfg.Telemetry)
	defer func() {
		if err := telemetryShutdown(context.Background()); err != nil {
			slog.Warn("otel: shutdown failed", "err", err)
		}
	}()

	slog.Info("starting", "issuer", cfg.Auth.Issuer, "listen", cfg.WebServer.Addr, "jwks_uri", cfg.Auth.JWKSUri)

	slog.Info("init: fetching JWKS")
	auth.MustInit(&cfg.Auth)
	slog.Info("init: JWKS ok, setting up OpenFeature provider")
	// SetupProvider returns a non-nil error when it falls back to the
	// from-env provider (missing creds / SSM init failure). Log it but
	// keep starting — flag evaluations still resolve via the fallback.
	startupErrors = initializeFeatureFlags(ctx, os.Getenv("ENVIRONMENT"), featureflags.AWSCredentials{
		AccessKeyID:     os.Getenv("AWS_ACCESS_KEY_ID"),
		SecretAccessKey: os.Getenv("AWS_SECRET_ACCESS_KEY"),
		Region:          os.Getenv("AWS_REGION"),
	})
	slog.Info("init: OpenFeature ok, loading OPA")
	auth.LoadOpa()
	slog.Info("init: OPA ok")

	// Start the Prometheus metrics server on a separate port so that it
	// doesn't compete with the main API server. The port is configurable
	// via METRICS_ADDR; the default :9091 avoids collision with the
	// in-namespace Prometheus deployment (which serves on :9090 / :80).
	metricsAddr := cfg.Metrics.Addr
	go func() {
		slog.Info("starting metrics server", "addr", metricsAddr)
		if err := metrics.StartMetricsServer(metricsAddr); err != nil {
			slog.Error("metrics server exited", "err", err)
		}
	}()

	admin := keycloak.NewAdmin(cfg.Keycloak.BaseURL, cfg.Keycloak.Realm, cfg.Keycloak.AdminClientID, cfg.Keycloak.AdminClientSecret, cfg.Auth.KeyClientPfx, cfg.Auth.UserKeyClientPfx)

	// Optional: admin client for the workloads realm, used to mint per-tenant
	// OIDC clients for OSGym pool VMs. Enabled only when its secret is set;
	// the admin client lives in the workloads realm because Keycloak
	// realm-management roles are per-realm. See
	// docs/decisions/2026-06-25-osgym-pool-workload-oidc.md.
	var workloadAdmin *keycloak.Admin
	if cfg.Keycloak.WorkloadAdminClientSecret != "" {
		workloadAdmin = keycloak.NewAdmin(
			cfg.Keycloak.BaseURL, cfg.Keycloak.WorkloadRealm,
			cfg.Keycloak.WorkloadAdminClientID, cfg.Keycloak.WorkloadAdminClientSecret,
			"", "",
		)
		slog.Info("workload-oidc: enabled", "realm", cfg.Keycloak.WorkloadRealm)
	} else {
		slog.Info("workload-oidc: disabled (KC_WORKLOAD_ADMIN_CLIENT_SECRET unset)")
	}

	h := handlers.New(admin, cfg)
	h.Analytics = analyticsClient
	lookupService, closeLookup, lookupErr := initializeAccountLookup(ctx, cfg, admin)
	h.AccountLookup = lookupService
	defer closeLookup()
	signedServiceURLsContext, cancelSignedServiceURLs := context.WithCancel(ctx)
	defer cancelSignedServiceURLs()
	var signedServiceURLsRetry sync.WaitGroup
	var signedServiceURLsMu sync.RWMutex
	var signedServiceURLs *signedurls.Service
	closeSignedServiceURLs := func() {}
	h.SignedServiceURLProvider = func() *signedurls.Service {
		signedServiceURLsMu.RLock()
		defer signedServiceURLsMu.RUnlock()
		return signedServiceURLs
	}
	installSignedServiceURLs := func(service *signedurls.Service, close func()) {
		signedServiceURLsMu.Lock()
		signedServiceURLs = service
		closeSignedServiceURLs = close
		signedServiceURLsMu.Unlock()
	}
	startupErrors = errors.Join(startupErrors, startSignedServiceURLs(ctx, signedServiceURLsContext, cfg.Database.URL, cfg.SignedServiceURL, &signedServiceURLsRetry, installSignedServiceURLs))
	defer shutdownSignedServiceURLs(cancelSignedServiceURLs, &signedServiceURLsRetry, &signedServiceURLsMu, &closeSignedServiceURLs)
	usageProvider, closeUsageProvider, err := initializeUsageProvider(ctx, cfg.Usage)
	if err != nil {
		return errors.Join(fmt.Errorf("initialize usage provider: %w", err), startupErrors, telemetryErr, lookupErr)
	}
	defer closeUsageProvider()
	h.Usage = usageProvider
	if usageProvider == nil {
		slog.Info("usage: disabled")
	} else {
		slog.Info("usage: enabled")
	}
	if cfg.Chat.BaseURL != "" {
		chatStorage := "memory"
		if cfg.Database.URL != "" {
			conversationStore, conversationStoreErr := chat.NewPostgresConversationStore(ctx, cfg.Database.URL)
			if conversationStoreErr != nil {
				return errors.Join(fmt.Errorf("initialize chat conversation store: %w", conversationStoreErr), startupErrors, telemetryErr, lookupErr)
			}
			defer conversationStore.Close()
			h.Conversations = conversationStore
			chatStorage = "postgres"
		} else {
			h.Conversations = chat.NewMemoryConversationStore()
		}
		h.Model = chat.NewLiteLLMClient(cfg.Chat.BaseURL, cfg.Chat.APIKey, cfg.Chat.Model)
		slog.Info("chat: configured", "base_url", cfg.Chat.BaseURL, "model", cfg.Chat.Model, "storage", chatStorage)
	} else {
		slog.Info("chat: not configured (LITELLM_BASE_URL and LITELLM_API_KEY unset)")
	}

	managementStore, processLocalManagement, managementStoreErr := featureFlagManagementStoreFromEnv(os.Getenv)
	if managementStoreErr != nil {
		startupErrors = errors.Join(startupErrors, managementStoreErr)
		slog.Warn("feature flag management: unavailable", "err", managementStoreErr)
		h.FeatureFlags = newUnsupportedFeatureFlagAdminService()
	} else if processLocalManagement {
		slog.Warn("feature flag management: ephemeral process-local store enabled")
		h.FeatureFlags = newFeatureFlagAdminService(managementStore, &processLocalMutationLock{})
	} else {
		leaseConfig := featureFlagLeaseConfigFromEnv(os.Getenv)
		lease := featureflagadmin.NewKubernetesLeaseLock(leaseConfig.apiBaseURL, leaseConfig.namespace, leaseConfig.name, leaseConfig.holderIdentity, 30*time.Second, 5*time.Second, time.Now)
		h.FeatureFlags = newFeatureFlagAdminService(managementStore, lease)
	}
	h.ImageObjects, err = newImageObjectStore(ctx, cfg.ImageUploads)
	if err != nil {
		return errors.Join(err, startupErrors, telemetryErr, lookupErr)
	}
	if h.ImageObjects != nil {
		slog.Info("image uploads: presigning enabled", "region", cfg.ImageUploads.Region)
	} else {
		slog.Info("image uploads: disabled (IMAGE_UPLOAD_BUCKET unset)")
	}
	if cfg.Stripe.SecretKey != "" {
		h.Billing = billing.NewService(billing.NewStripeGateway(cfg.Stripe.SecretKey))
		slog.Info("stripe billing: hosted flows enabled")
	} else {
		slog.Info("stripe billing: disabled (STRIPE_SECRET_KEY unset)")
	}
	h.WebhookVerifier = billing.NewStripeWebhookVerifier()
	h.WorkloadAdmin = workloadAdmin
	h.WorkloadAudience = cfg.Keycloak.WorkloadAudience
	h.WorkloadTokenURL = cfg.Keycloak.WorkloadTokenURL
	// Install the trust resolver once, bound to the feature registry rather
	// than to a store instance: auth keeps it in an unguarded package global
	// that every request reads, so rewriting it from the retry goroutine below
	// would be a data race.
	auth.SetGitHubTrustResolver(handlers.NewGitHubTrustResolverFor(h.Features))
	databaseFeatures := defaultDatabaseFeatureDependencies()
	progress := initializeDatabaseFeatures(ctx, cfg.Database, &h, databaseFeatures)
	go retryDatabaseFeatures(ctx, cfg.Database, &h, databaseFeatures, progress, databaseRetryInterval)

	router := setupRouter(h)

	srv := &http.Server{Addr: cfg.WebServer.Addr, Handler: router}
	return errors.Join(serveUntilCanceled(ctx, srv), startupErrors, telemetryErr, lookupErr)
}

// Lazy pool connections keep this optional feature independent of serving readiness.
func initializeAccountLookup(ctx context.Context, cfg *config.Configuration, admin *keycloak.Admin) (*accountlookup.Service, func(), error) {
	if cfg.Database.URL == "" || cfg.ProductAnalytics.IdentityKey == "" {
		return nil, func() {}, nil
	}
	store, err := accountlookup.NewStore(ctx, cfg.Database.URL)
	if err != nil {
		slog.Warn("account lookup unavailable: invalid database configuration")
		return nil, func() {}, err
	}
	lookupCtx, cancel := context.WithCancel(ctx)
	service := accountlookup.New(lookupCtx, store, admin, cfg.Keycloak.Realm, cfg.ProductAnalytics.IdentityKey, cfg.ProductAnalytics.ExcludedSubjects)
	return service, func() { cancel(); service.Wait(); store.Close() }, nil
}

// startSignedServiceURLs installs the signed service URL dependency on first
// try, or arms the background retry loop and reports the degradation so run()
// can fold it into the startup error set. Serving stays up either way; the
// routes answer 503 until a retry succeeds.
func startSignedServiceURLs(ctx, retryCtx context.Context, databaseURL string, cfg config.SignedServiceURLConfiguration, retry *sync.WaitGroup, install func(*signedurls.Service, func())) error {
	service, close, err := initializeSignedServiceURLs(ctx, databaseURL, cfg)
	if err == nil {
		install(service, close)
		return nil
	}
	slog.Error("signed service URLs: initialization unavailable; routes will return 503", "class", "dependency_unavailable", "retryable", true)
	retry.Add(1)
	go func() {
		defer retry.Done()
		ticker := time.NewTicker(databaseRetryInterval)
		defer ticker.Stop()
		for {
			select {
			case <-retryCtx.Done():
				return
			case <-ticker.C:
				service, close, err := initializeSignedServiceURLs(retryCtx, databaseURL, cfg)
				if err == nil {
					install(service, close)
					slog.Info("signed service URLs: recovered without a restart")
					return
				}
			}
		}
	}()
	return fmt.Errorf("initialize signed service URLs: %w", err)
}

func shutdownSignedServiceURLs(cancel context.CancelFunc, retry *sync.WaitGroup, mu *sync.RWMutex, closeStore *func()) {
	cancel()
	retry.Wait()
	mu.Lock()
	close := *closeStore
	*closeStore = func() {}
	mu.Unlock()
	close()
}

func initializeSignedServiceURLs(ctx context.Context, databaseURL string, cfg config.SignedServiceURLConfiguration) (*signedurls.Service, func(), error) {
	secret, err := signedServiceURLSecret(cfg)
	if err != nil {
		return nil, func() {}, err
	}

	missing := make([]string, 0, 3)
	if databaseURL == "" {
		missing = append(missing, "DATABASE_URL")
	}
	if cfg.BaseURL == "" {
		missing = append(missing, "SIGNED_SERVICE_URL_BASE_URL")
	}
	if secret == "" {
		missing = append(missing, "SIGNED_SERVICE_URL_SECRET")
	}
	if len(missing) > 0 {
		slog.Info("signed service URLs: disabled", "missing_configuration_keys", missing)
		return nil, func() {}, nil
	}

	store, err := signedurls.NewPostgresStore(ctx, databaseURL)
	if err != nil {
		return nil, func() {}, fmt.Errorf("initialize signed URL store: %w", err)
	}
	signer, err := signedurls.NewSigner(cfg.BaseURL, []byte(secret))
	if err != nil {
		store.Close()
		return nil, func() {}, fmt.Errorf("initialize signed URL signer: %w", err)
	}
	return signedurls.NewService(store, signer), store.Close, nil
}

func signedServiceURLSecret(cfg config.SignedServiceURLConfiguration) (string, error) {
	if cfg.Secret != "" {
		return validateSignedServiceURLSecret("SIGNED_SERVICE_URL_SECRET", cfg.Secret)
	}
	if cfg.SecretFile == "" {
		return "", nil
	}

	contents, err := os.ReadFile(cfg.SecretFile)
	if err != nil {
		return "", fmt.Errorf("read SIGNED_SERVICE_URL_SECRET_FILE: %w", err)
	}
	return validateSignedServiceURLSecret("SIGNED_SERVICE_URL_SECRET_FILE", strings.TrimSpace(string(contents)))
}

func validateSignedServiceURLSecret(name, secret string) (string, error) {
	if secret == "" {
		return "", fmt.Errorf("%s must not be empty", name)
	}
	if len([]byte(secret)) < sha256.Size {
		return "", fmt.Errorf("%s must be at least %d bytes", name, sha256.Size)
	}
	return secret, nil
}

func serveUntilCanceled(ctx context.Context, server *http.Server) error {
	serverErrors := make(chan error, 1)
	go func() {
		serverErrors <- server.ListenAndServe()
	}()

	select {
	case err := <-serverErrors:
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return fmt.Errorf("server exited: %w", err)
	case <-ctx.Done():
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		shutdownErr := server.Shutdown(shutdownCtx)
		serverErr := <-serverErrors
		if errors.Is(serverErr, http.ErrServerClosed) {
			serverErr = nil
		}
		return errors.Join(shutdownErr, serverErr)
	}
}

func newFeatureFlagAdminService(store featureflags.ManagementStore, lock featureflagadmin.MutationLock) *featureflagadmin.Service {
	return featureflagadmin.NewService(store, lock, cacheInvalidator{}, featureflagadmin.NewSlogAuditLogger(nil))
}

func newUnsupportedFeatureFlagAdminService() *featureflagadmin.Service {
	return featureflagadmin.NewUnsupportedService(featureflagadmin.NewSlogAuditLogger(nil))
}

type cacheInvalidator struct{}

func (cacheInvalidator) InvalidateFeatureFlags() { auth.InvalidateFeatureFlags() }

type featureFlagLeaseConfig struct {
	apiBaseURL     string
	namespace      string
	name           string
	holderIdentity string
}

func featureFlagLeaseConfigFromEnv(getenv func(string) string) featureFlagLeaseConfig {
	valueOrDefault := func(key, fallback string) string {
		if value := getenv(key); value != "" {
			return value
		}
		return fallback
	}
	return featureFlagLeaseConfig{
		apiBaseURL:     valueOrDefault("KUBERNETES_PROXY_URL", "http://127.0.0.1:8001"),
		namespace:      valueOrDefault("FEATURE_FLAG_LEASE_NAMESPACE", "cyclops-cs"),
		name:           valueOrDefault("FEATURE_FLAG_LEASE_NAME", "cyclops-feature-flags-writer"),
		holderIdentity: getenv("HOSTNAME"),
	}
}

const (
	databaseStartupTimeout = 5 * time.Second
	// How often a degraded pod re-attempts its database dependencies.
	databaseRetryInterval = 30 * time.Second
)

type databaseFeatureDependencies struct {
	requireVersion        func(context.Context, string, int64) error
	newStateQueryExecutor func(string, string) (handlers.StateQueryExecutor, error)
	newGitHubTrustStore   func(context.Context, string) (githubtrust.Store, error)
}

func defaultDatabaseFeatureDependencies() databaseFeatureDependencies {
	return databaseFeatureDependencies{
		requireVersion: database.RequireVersion,
		newStateQueryExecutor: func(dsn, tenantPassword string) (handlers.StateQueryExecutor, error) {
			return statequery.NewExecutor(dsn, tenantPassword)
		},
		newGitHubTrustStore: githubtrust.New,
	}
}

// featureProgress records which database-backed dependencies are up, so a
// retry only re-attempts what is still missing. Re-running the whole
// initialization would clear a working state query executor every time it
// retried a broken application database.
type featureProgress struct {
	stateQuery    bool
	applicationDB bool
}

func (p featureProgress) ready() bool { return p.stateQuery && p.applicationDB }

// initializeDatabaseFeatures is the startup path: it clears anything stale and
// installs whatever is configured, reporting what came up.
func initializeDatabaseFeatures(parent context.Context, cfg config.DatabaseConfiguration, h *handlers.Handlers, dependencies databaseFeatureDependencies) featureProgress {
	h.Features.SetStateQuery(nil)
	h.Features.SetTrustStore(nil)

	return attemptDatabaseFeatures(parent, cfg, h, dependencies, featureProgress{})
}

// attemptDatabaseFeatures installs whatever is configured and not already up,
// leaving working dependencies untouched so it is safe to call repeatedly.
func attemptDatabaseFeatures(parent context.Context, cfg config.DatabaseConfiguration, h *handlers.Handlers, dependencies databaseFeatureDependencies, progress featureProgress) featureProgress {
	// The state query executor has its own DSN and its own failure path: it is
	// initialized before the DATABASE_URL short-circuit below and a failure
	// here does not stop the rest of this function, so it needs its own gauge.
	// Reporting it through DatabaseFeaturesReady would claim a healthy
	// /api/state/query whenever the application database came up fine.
	switch {
	case cfg.StateQueryDSN == "" || cfg.StateQueryTenantPassword == "":
		metrics.StateQueryReady.WithLabelValues("false").Set(1)
		progress.stateQuery = true
	case progress.stateQuery:
		// Already up; leave it alone.
	default:
		executor, err := dependencies.newStateQueryExecutor(cfg.StateQueryDSN, cfg.StateQueryTenantPassword)
		if err != nil {
			slog.Error("kubernetes state query: executor init failed; /api/state/query will return 503",
				"class", "state_query_initialization_failed", "retryable", false)
			metrics.StateQueryReady.WithLabelValues("true").Set(0)
		} else {
			h.Features.SetStateQuery(executor)
			metrics.StateQueryReady.WithLabelValues("true").Set(1)
			progress.stateQuery = true
			slog.Info("kubernetes state query: query endpoint enabled")
		}
	}

	if cfg.URL == "" {
		slog.Info("postgres-backed features disabled (DATABASE_URL unset)")
		metrics.DatabaseFeaturesReady.WithLabelValues("false").Set(1)
		progress.applicationDB = true
		return progress
	}
	if progress.applicationDB {
		return progress
	}

	// Every path below reports through this gauge. Readiness stays
	// database-independent by design, so this metric is the only way an
	// operator learns that a serving pod came up degraded.
	metrics.DatabaseFeaturesReady.WithLabelValues("true").Set(0)

	// Deliberately the same budget on the retry path: a database that cannot
	// answer within databaseStartupTimeout is still down as far as this pod is
	// concerned, and a longer budget would only stretch the tick.
	ctx, cancel := context.WithTimeout(parent, databaseStartupTimeout)
	defer cancel()

	if err := dependencies.requireVersion(ctx, cfg.URL, 1); err != nil {
		classification := database.ClassifyError(err)
		slog.Error("postgres database schema unavailable; database-backed routes will return 503",
			"class", classification.Class, "retryable", classification.Retryable)
		return progress
	}
	slog.Info("postgres database schema ready", "version", 1)

	store, err := dependencies.newGitHubTrustStore(ctx, cfg.URL)
	if err != nil {
		classification := database.ClassifyError(err)
		slog.Error("github trust policies: init failed; /api/github-trust-policies will return 503",
			"class", classification.Class, "retryable", classification.Retryable)
		return progress
	}
	if store != nil {
		h.Features.SetTrustStore(store)
		slog.Info("github trust policies: enabled")
	}

	metrics.DatabaseFeaturesReady.WithLabelValues("true").Set(1)
	progress.applicationDB = true
	return progress
}

// retryDatabaseFeatures re-attempts the dependencies that did not come up at
// startup until they do, then stops. Without it a pod that started during a
// database outage stays degraded until someone restarts it: initialization runs
// once, and the serving tier deliberately keeps the pod Ready throughout, so
// nothing else would ever notice.
//
// This is only reachable because the dependencies live behind handlers.Features
// rather than in the Handlers copy the router captured.
//
// ctx is run()'s context.Background(), which nothing cancels today, so in
// production this goroutine ends with the process. The ctx.Done() case is for
// tests, and for the day run() grows a real shutdown context.
func retryDatabaseFeatures(ctx context.Context, cfg config.DatabaseConfiguration, h *handlers.Handlers, dependencies databaseFeatureDependencies, progress featureProgress, interval time.Duration) {
	if progress.ready() {
		return
	}
	slog.Warn("database features degraded at startup; retrying in the background", "interval", interval)

	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			progress = attemptDatabaseFeatures(ctx, cfg, h, dependencies, progress)
			if progress.ready() {
				slog.Info("database features recovered without a restart")
				return
			}
		}
	}
}

func initializeUsageProvider(ctx context.Context, cfg config.UsageConfiguration) (usage.Provider, func(), error) {
	noop := func() {}
	// Query transport settings are deployed independently from the read-only
	// usage credential. Keep the provider disabled until the database URL arrives.
	if cfg.DatabaseURL == "" {
		return nil, noop, nil
	}
	events, err := usage.NewPostgresEventStore(ctx, cfg.DatabaseURL)
	if err != nil {
		return nil, noop, fmt.Errorf("create usage event store: %w", err)
	}
	allocations, err := usage.NewDataFusionAllocationClient(
		cfg.QueryWebhookURL,
		cfg.QueryHMACSecret,
		cfg.QueryResultBucket,
		cfg.QueryResultPrefix,
		cfg.QueryCluster,
		cfg.QueryEnvironment,
		cfg.QueryTimeout,
		cfg.QueryPollInterval,
		cfg.MaxResponseBytes,
		usage.NewS3QueryObjectStore(),
	)
	if err != nil {
		events.Close()
		return nil, noop, fmt.Errorf("create DataFusion allocation client: %w", err)
	}
	return usage.NewProviderWithReservations(events, allocations, events, cfg.QueryCluster, nil), events.Close, nil
}
