// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

import lib from "./node-runtime.js";
const { UniffiNativeModule, FfiType, resolveLibPath } = lib;

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from '@ubjs/core';

const DEFINITIONS = {
  symbols: {
    rustbuffer_alloc: "ffi_cua_driver_sdk_rustbuffer_alloc",
    rustbuffer_free: "ffi_cua_driver_sdk_rustbuffer_free",
    rustbuffer_from_bytes: "ffi_cua_driver_sdk_rustbuffer_from_bytes",
  },
  functions: {
    "ffi_cua_driver_sdk_rust_future_poll_u8": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_u8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_u8": {
      args: [FfiType.Handle],
      ret: FfiType.UInt8,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_u8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_i8": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_u16": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_u16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_u16": {
      args: [FfiType.Handle],
      ret: FfiType.UInt16,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_u16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_i16": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Int16,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_u32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_u32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_u32": {
      args: [FfiType.Handle],
      ret: FfiType.UInt32,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_u32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_i32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Int32,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_u64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_i64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Int64,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_f32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Float32,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_f64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Float64,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_rust_buffer": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_poll_void": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_cancel_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cua_driver_sdk_rust_future_complete_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_rust_future_free_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_clone_cuadriver": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_free_cuadriver": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_clone_cuadriversession": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_free_cuadriversession": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_clone_driveractivityobserver": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_free_driveractivityobserver": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_clone_driverauthorizationhost": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_free_driverauthorizationhost": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_clone_driverservicetransport": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_free_driverservicetransport": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_clone_embeddedcuadriverhost": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_free_embeddedcuadriverhost": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_clone_foreigndriverenvelopechannel": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_free_foreigndriverenvelopechannel": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_clone_mcpdriverchannel": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_free_mcpdriverchannel": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_init_callback_vtable_driveractivityobserver": {
      args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceCuaDriverSdkDriverActivityObserver"))],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_init_callback_vtable_driverauthorizationhost": {
      args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceCuaDriverSdkDriverAuthorizationHost"))],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_init_callback_vtable_driverservicetransport": {
      args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceCuaDriverSdkDriverServiceTransport"))],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_init_callback_vtable_foreigndriverenvelopechannel": {
      args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannel"))],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_func_connect_remote_channel": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_func_create_remote_trusted_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_func_create_trusted_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_func_current_mac_os_permission_status": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_func_open_mac_os_screen_recording_settings": {
      args: [],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_func_open_mcp_driver_channel": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_func_request_mac_os_permissions": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect_with_client_kind": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_activity_observer": {
      args: [FfiType.RustBuffer, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_activity_observer_and_client_kind": {
      args: [FfiType.RustBuffer, FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_authorization_host": {
      args: [FfiType.RustBuffer, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_authorization_host_and_client_kind": {
      args: [FfiType.RustBuffer, FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_client_kind": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_host_integrations": {
      args: [FfiType.RustBuffer, FfiType.Handle, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_host_integrations_and_client_kind": {
      args: [FfiType.RustBuffer, FfiType.Handle, FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_private_worker": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_private_worker_with_client_kind": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_with_client_kind": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool_with_id": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_cancel_call": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_click": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_clipboard_read": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_clipboard_write": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_drag": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_end_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_escalate_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_execution_mode": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_get_agent_cursor_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_get_cursor_position": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_get_desktop_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_get_screen_size": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_get_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_get_session_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_get_window_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_hotkey": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_invoke_menu": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_is_available": {
      args: [FfiType.Handle],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_list_apps": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_list_host_sessions_json": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_list_sessions": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_list_tools_json": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_list_windows": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_metadata": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_move_cursor": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_press_key": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_runtime_scope_prefix": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_scroll": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_enabled": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_motion": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_theme": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_set_window_frame": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_shutdown": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_socket_path": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_start_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_type_text": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriver_verify_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_call_tool": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_click": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_clipboard_read": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_clipboard_write": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_close": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_drag": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_end_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_escalate_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_agent_cursor_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_cursor_position": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_desktop_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_screen_size": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_session_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_window_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_hotkey": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_invoke_menu": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_list_apps": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_list_sessions": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_list_windows": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_move_cursor": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_press_key": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_scroll": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_enabled": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_motion": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_theme": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_set_window_frame": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_start_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_type_text": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_cuadriversession_verify_state": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_driveractivityobserver_on_activity": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_driverauthorizationhost_authorize": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_driverservicetransport_send": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_constructor_embeddedcuadriverhost_new": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_constructor_embeddedcuadriverhost_with_options": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_connection": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_restart": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_start": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_state": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_stop": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_wait_for_exit": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_identity": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_negotiate": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_exchange": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_bind_session": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_cancel": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_close": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_mcpdriverchannel_close": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_mcpdriverchannel_driver": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cua_driver_sdk_fn_method_mcpdriverchannel_open": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_fn_method_mcpdriverchannel_public_session": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "ffi_cua_driver_sdk_uniffi_contract_version": {
      args: [],
      ret: FfiType.UInt32,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_func_connect_remote_channel": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_func_create_remote_trusted_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_func_create_trusted_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_func_current_mac_os_permission_status": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_func_open_mac_os_screen_recording_settings": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_func_open_mcp_driver_channel": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_func_request_mac_os_permissions": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect_with_client_kind": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_activity_observer": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_activity_observer_and_client_kind": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_authorization_host": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_authorization_host_and_client_kind": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_client_kind": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_host_integrations": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_host_integrations_and_client_kind": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_private_worker": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_private_worker_with_client_kind": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_with_client_kind": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool_with_id": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_cancel_call": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_click": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_clipboard_read": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_clipboard_write": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_drag": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_end_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_escalate_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_execution_mode": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_agent_cursor_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_cursor_position": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_desktop_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_screen_size": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_window_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_hotkey": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_invoke_menu": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_is_available": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_list_apps": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_list_host_sessions_json": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_list_sessions": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_list_tools_json": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_list_windows": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_metadata": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_move_cursor": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_press_key": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_runtime_scope_prefix": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_scroll": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_enabled": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_motion": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_theme": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_set_window_frame": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_shutdown": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_socket_path": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_start_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_type_text": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriver_verify_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_call_tool": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_click": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_clipboard_read": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_clipboard_write": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_close": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_drag": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_end_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_escalate_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_agent_cursor_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_cursor_position": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_desktop_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_screen_size": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_session_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_window_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_hotkey": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_invoke_menu": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_list_apps": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_list_sessions": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_list_windows": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_move_cursor": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_press_key": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_scroll": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_enabled": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_motion": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_theme": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_window_frame": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_start_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_type_text": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_cuadriversession_verify_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_driveractivityobserver_on_activity": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_driverauthorizationhost_authorize": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_driverservicetransport_send": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_embeddedcuadriverhost_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_constructor_embeddedcuadriverhost_with_options": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_connection": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_restart": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_start": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_state": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_stop": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_wait_for_exit": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_identity": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_negotiate": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_exchange": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_bind_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_cancel": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_close": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_mcpdriverchannel_close": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_mcpdriverchannel_driver": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_mcpdriverchannel_open": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cua_driver_sdk_checksum_method_mcpdriverchannel_public_session": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
  },
  callbacks: {
    "RustFutureContinuationCallback": {
      args: [FfiType.Handle, FfiType.Int8],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ForeignFutureDroppedCallback": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceCuaDriverSdkDriverActivityObserverMethod0": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.VoidPointer,
      hasRustCallStatus: true,
      outReturn: true,
    },
    "CallbackInterfaceCloneCuaDriverSdk_DriverActivityObserver": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFreeCuaDriverSdk_DriverActivityObserver": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ForeignFutureCompleterust_buffer": {
      args: [FfiType.Handle, FfiType.Struct("ForeignFutureResultRustBuffer")],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceCuaDriverSdkDriverAuthorizationHostMethod0": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceCloneCuaDriverSdk_DriverAuthorizationHost": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFreeCuaDriverSdk_DriverAuthorizationHost": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceCuaDriverSdkDriverServiceTransportMethod0": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceCloneCuaDriverSdk_DriverServiceTransport": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFreeCuaDriverSdk_DriverServiceTransport": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod0": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
      outReturn: true,
    },
    "CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod1": {
      args: [FfiType.Handle, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod2": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod3": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "ForeignFutureCompletevoid": {
      args: [FfiType.Handle, FfiType.Struct("ForeignFutureResultVoid")],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod4": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompletevoid"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod5": {
      args: [FfiType.Handle, FfiType.Callback("ForeignFutureCompletevoid"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceCloneCuaDriverSdk_ForeignDriverEnvelopeChannel": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFreeCuaDriverSdk_ForeignDriverEnvelopeChannel": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
  },
  structs: {
    "ForeignFutureDroppedCallbackStruct": [
      { name: "handle", type: FfiType.Handle },
      { name: "free", type: FfiType.Callback("ForeignFutureDroppedCallback") },
    ],
    "VTableCallbackInterfaceCuaDriverSdkDriverActivityObserver": [
      { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeCuaDriverSdk_DriverActivityObserver") },
      { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneCuaDriverSdk_DriverActivityObserver") },
      { name: "on_activity", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkDriverActivityObserverMethod0") },
    ],
    "ForeignFutureResultRustBuffer": [
      { name: "return_value", type: FfiType.RustBuffer },
      { name: "call_status", type: FfiType.RustCallStatus },
    ],
    "VTableCallbackInterfaceCuaDriverSdkDriverAuthorizationHost": [
      { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeCuaDriverSdk_DriverAuthorizationHost") },
      { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneCuaDriverSdk_DriverAuthorizationHost") },
      { name: "authorize", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkDriverAuthorizationHostMethod0") },
    ],
    "VTableCallbackInterfaceCuaDriverSdkDriverServiceTransport": [
      { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeCuaDriverSdk_DriverServiceTransport") },
      { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneCuaDriverSdk_DriverServiceTransport") },
      { name: "send", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkDriverServiceTransportMethod0") },
    ],
    "ForeignFutureResultVoid": [
      { name: "call_status", type: FfiType.RustCallStatus },
    ],
    "VTableCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannel": [
      { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeCuaDriverSdk_ForeignDriverEnvelopeChannel") },
      { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneCuaDriverSdk_ForeignDriverEnvelopeChannel") },
      { name: "identity", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod0") },
      { name: "negotiate", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod1") },
      { name: "exchange", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod2") },
      { name: "bind_session", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod3") },
      { name: "cancel", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod4") },
      { name: "close", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod5") },
    ],
  },
} as const;

interface NativeModuleInterface {
    ffi_cua_driver_sdk_rust_future_poll_u8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_u8(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_u8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_u8(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_i8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_i8(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_i8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_i8(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_u16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_u16(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_u16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_u16(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_i16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_i16(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_i16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_i16(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_u32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_u32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_u32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_u32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_i32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_i32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_i32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_i32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_u64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_u64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_u64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cua_driver_sdk_rust_future_free_u64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_i64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_i64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_i64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cua_driver_sdk_rust_future_free_i64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_f32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_f32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_f32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_f32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_f64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_f64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_f64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_f64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_rust_buffer(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_rust_buffer(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_rust_buffer(handle: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ffi_cua_driver_sdk_rust_future_free_rust_buffer(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_void(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_void(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_void(handle: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    ffi_cua_driver_sdk_rust_future_free_void(handle: bigint): void;
    uniffi_cua_driver_sdk_fn_clone_cuadriver(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_cuadriver(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_cuadriversession(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_cuadriversession(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_driveractivityobserver(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_driveractivityobserver(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_driverauthorizationhost(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_driverauthorizationhost(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_driverservicetransport(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_driverservicetransport(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_embeddedcuadriverhost(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_embeddedcuadriverhost(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_foreigndriverenvelopechannel(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_foreigndriverenvelopechannel(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_mcpdriverchannel(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_mcpdriverchannel(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_init_callback_vtable_driveractivityobserver(vtable: UniffiVTableCallbackInterfaceCuaDriverSdkDriverActivityObserver): void;
    uniffi_cua_driver_sdk_fn_init_callback_vtable_driverauthorizationhost(vtable: UniffiVTableCallbackInterfaceCuaDriverSdkDriverAuthorizationHost): void;
    uniffi_cua_driver_sdk_fn_init_callback_vtable_driverservicetransport(vtable: UniffiVTableCallbackInterfaceCuaDriverSdkDriverServiceTransport): void;
    uniffi_cua_driver_sdk_fn_init_callback_vtable_foreigndriverenvelopechannel(vtable: UniffiVTableCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannel): void;
    uniffi_cua_driver_sdk_fn_func_connect_remote_channel(channel: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_func_create_remote_trusted_session(driver: bigint, options: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_func_create_trusted_session(driver: bigint, options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_func_current_mac_os_permission_status(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_func_open_mac_os_screen_recording_settings(uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_func_open_mcp_driver_channel(transport: bigint, authenticatedPrincipal: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_func_request_mac_os_permissions(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect(socketPath: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect_with_client_kind(socketPath: Uint8Array, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create(options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured(options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_activity_observer(options: Uint8Array, observer: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_activity_observer_and_client_kind(options: Uint8Array, observer: bigint, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_authorization_host(options: Uint8Array, host: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_authorization_host_and_client_kind(options: Uint8Array, host: bigint, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_client_kind(options: Uint8Array, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_host_integrations(options: Uint8Array, host: bigint, observer: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_host_integrations_and_client_kind(options: Uint8Array, host: bigint, observer: bigint, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_private_worker(options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_private_worker_with_client_kind(options: Uint8Array, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_with_client_kind(options: Uint8Array, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool(uniffiSelf: bigint, name: Uint8Array, argumentsJson: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool_with_id(uniffiSelf: bigint, callId: Uint8Array, name: Uint8Array, argumentsJson: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_cancel_call(uniffiSelf: bigint, callId: Uint8Array, uniffi_out_err: UniffiRustCallStatus): number;
    uniffi_cua_driver_sdk_fn_method_cuadriver_click(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_clipboard_read(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_clipboard_write(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_drag(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_end_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_escalate_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_execution_mode(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_agent_cursor_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_cursor_position(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_desktop_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_screen_size(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_session_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_window_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_hotkey(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_invoke_menu(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_is_available(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    uniffi_cua_driver_sdk_fn_method_cuadriver_list_apps(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_list_host_sessions_json(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_list_sessions(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_list_tools_json(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_list_windows(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_metadata(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_move_cursor(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_press_key(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_runtime_scope_prefix(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_cuadriver_scroll(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_enabled(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_motion(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_theme(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_set_window_frame(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_shutdown(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_socket_path(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_cuadriver_start_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_type_text(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_verify_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_call_tool(uniffiSelf: bigint, name: Uint8Array, argumentsJson: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_click(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_clipboard_read(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_clipboard_write(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_close(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_drag(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_end_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_escalate_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_agent_cursor_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_cursor_position(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_desktop_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_screen_size(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_session_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_window_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_hotkey(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_invoke_menu(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_list_apps(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_list_sessions(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_list_windows(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_move_cursor(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_press_key(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_scroll(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_enabled(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_motion(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_theme(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_set_window_frame(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_start_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_type_text(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_verify_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_driveractivityobserver_on_activity(uniffiSelf: bigint, event: Uint8Array, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_method_driverauthorizationhost_authorize(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_driverservicetransport_send(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_constructor_embeddedcuadriverhost_new(binaryPath: Uint8Array, hostBundleId: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_embeddedcuadriverhost_with_options(options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_connection(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_restart(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_start(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_state(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_stop(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_wait_for_exit(uniffiSelf: bigint, generation: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_identity(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_negotiate(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_exchange(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_bind_session(uniffiSelf: bigint, options: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_cancel(uniffiSelf: bigint, requestId: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_foreigndriverenvelopechannel_close(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_mcpdriverchannel_close(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_mcpdriverchannel_driver(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_method_mcpdriverchannel_open(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_mcpdriverchannel_public_session(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ffi_cua_driver_sdk_uniffi_contract_version(): number;
    uniffi_cua_driver_sdk_checksum_func_connect_remote_channel(): number;
    uniffi_cua_driver_sdk_checksum_func_create_remote_trusted_session(): number;
    uniffi_cua_driver_sdk_checksum_func_create_trusted_session(): number;
    uniffi_cua_driver_sdk_checksum_func_current_mac_os_permission_status(): number;
    uniffi_cua_driver_sdk_checksum_func_open_mac_os_screen_recording_settings(): number;
    uniffi_cua_driver_sdk_checksum_func_open_mcp_driver_channel(): number;
    uniffi_cua_driver_sdk_checksum_func_request_mac_os_permissions(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect_with_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_activity_observer(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_activity_observer_and_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_authorization_host(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_authorization_host_and_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_host_integrations(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_host_integrations_and_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_private_worker(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_private_worker_with_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_with_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool_with_id(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_cancel_call(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_click(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_clipboard_read(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_clipboard_write(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_drag(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_end_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_escalate_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_execution_mode(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_agent_cursor_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_cursor_position(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_desktop_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_screen_size(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_window_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_hotkey(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_invoke_menu(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_is_available(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_list_apps(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_list_host_sessions_json(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_list_sessions(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_list_tools_json(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_list_windows(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_metadata(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_move_cursor(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_press_key(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_runtime_scope_prefix(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_scroll(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_enabled(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_motion(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_theme(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_set_window_frame(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_shutdown(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_socket_path(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_start_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_type_text(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_verify_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_call_tool(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_click(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_clipboard_read(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_clipboard_write(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_close(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_drag(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_end_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_escalate_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_agent_cursor_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_cursor_position(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_desktop_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_screen_size(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_session_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_window_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_hotkey(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_invoke_menu(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_list_apps(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_list_sessions(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_list_windows(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_move_cursor(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_press_key(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_scroll(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_enabled(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_motion(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_theme(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_window_frame(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_start_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_type_text(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_verify_state(): number;
    uniffi_cua_driver_sdk_checksum_method_driveractivityobserver_on_activity(): number;
    uniffi_cua_driver_sdk_checksum_method_driverauthorizationhost_authorize(): number;
    uniffi_cua_driver_sdk_checksum_method_driverservicetransport_send(): number;
    uniffi_cua_driver_sdk_checksum_constructor_embeddedcuadriverhost_new(): number;
    uniffi_cua_driver_sdk_checksum_constructor_embeddedcuadriverhost_with_options(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_connection(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_restart(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_start(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_state(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_stop(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_wait_for_exit(): number;
    uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_identity(): number;
    uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_negotiate(): number;
    uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_exchange(): number;
    uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_bind_session(): number;
    uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_cancel(): number;
    uniffi_cua_driver_sdk_checksum_method_foreigndriverenvelopechannel_close(): number;
    uniffi_cua_driver_sdk_checksum_method_mcpdriverchannel_close(): number;
    uniffi_cua_driver_sdk_checksum_method_mcpdriverchannel_driver(): number;
    uniffi_cua_driver_sdk_checksum_method_mcpdriverchannel_open(): number;
    uniffi_cua_driver_sdk_checksum_method_mcpdriverchannel_public_session(): number;
    // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
    // and `nativeModule().rustbuffer_free(...)`. The runtime's registered
    // module exposes them as method properties.
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}

let _nativeModule: NativeModuleInterface | undefined;
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    const libPath = resolveLibPath({
      crateName: "cua_driver_sdk",
      callerUrl: import.meta.url,
      npmPackageBase: "@trycua/cua-driver-",
      tripleStyle: "node",
    });
    const mod_ = UniffiNativeModule.open(libPath);
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface;
  }
  return _nativeModule;
};
export default getter;

// Structs and function types for calling back into Typescript from Rust.
export type UniffiRustFutureContinuationCallback = (data: bigint, pollResult: number) => void;
export type UniffiForeignFutureDroppedCallback = (handle: bigint) => void;
export type UniffiForeignFutureDroppedCallbackStruct = {
  handle: bigint;
  free: UniffiForeignFutureDroppedCallback;
};
type UniffiCallbackInterfaceCuaDriverSdkDriverActivityObserverMethod0 = (uniffiHandle: bigint, event: Uint8Array) => UniffiResult<void>;
type UniffiCallbackInterfaceCloneCuaDriverSdkDriverActivityObserver = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeCuaDriverSdkDriverActivityObserver = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceCuaDriverSdkDriverActivityObserver = {
  uniffi_free: UniffiCallbackInterfaceFreeCuaDriverSdkDriverActivityObserver;
  uniffi_clone: UniffiCallbackInterfaceCloneCuaDriverSdkDriverActivityObserver;
  on_activity: UniffiCallbackInterfaceCuaDriverSdkDriverActivityObserverMethod0;
};
export type UniffiForeignFutureResultRustBuffer = {
  return_value: Uint8Array;
  call_status: UniffiRustCallStatus;
};
export type UniffiForeignFutureCompleterustBuffer = (callbackData: bigint, result: UniffiForeignFutureResultRustBuffer) => void;
type UniffiCallbackInterfaceCuaDriverSdkDriverAuthorizationHostMethod0 = (uniffiHandle: bigint, request: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCloneCuaDriverSdkDriverAuthorizationHost = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeCuaDriverSdkDriverAuthorizationHost = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceCuaDriverSdkDriverAuthorizationHost = {
  uniffi_free: UniffiCallbackInterfaceFreeCuaDriverSdkDriverAuthorizationHost;
  uniffi_clone: UniffiCallbackInterfaceCloneCuaDriverSdkDriverAuthorizationHost;
  authorize: UniffiCallbackInterfaceCuaDriverSdkDriverAuthorizationHostMethod0;
};
type UniffiCallbackInterfaceCuaDriverSdkDriverServiceTransportMethod0 = (uniffiHandle: bigint, request: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCloneCuaDriverSdkDriverServiceTransport = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeCuaDriverSdkDriverServiceTransport = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceCuaDriverSdkDriverServiceTransport = {
  uniffi_free: UniffiCallbackInterfaceFreeCuaDriverSdkDriverServiceTransport;
  uniffi_clone: UniffiCallbackInterfaceCloneCuaDriverSdkDriverServiceTransport;
  send: UniffiCallbackInterfaceCuaDriverSdkDriverServiceTransportMethod0;
};
type UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod0 = (uniffiHandle: bigint) => Uint8Array;
type UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod1 = (uniffiHandle: bigint, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod2 = (uniffiHandle: bigint, request: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod3 = (uniffiHandle: bigint, options: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
export type UniffiForeignFutureResultVoid = {
  call_status: UniffiRustCallStatus;
};
export type UniffiForeignFutureCompletevoid = (callbackData: bigint, result: UniffiForeignFutureResultVoid) => void;
type UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod4 = (uniffiHandle: bigint, requestId: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompletevoid, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod5 = (uniffiHandle: bigint, uniffiFutureCallback: UniffiForeignFutureCompletevoid, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCloneCuaDriverSdkForeignDriverEnvelopeChannel = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeCuaDriverSdkForeignDriverEnvelopeChannel = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannel = {
  uniffi_free: UniffiCallbackInterfaceFreeCuaDriverSdkForeignDriverEnvelopeChannel;
  uniffi_clone: UniffiCallbackInterfaceCloneCuaDriverSdkForeignDriverEnvelopeChannel;
  identity: UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod0;
  negotiate: UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod1;
  exchange: UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod2;
  bind_session: UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod3;
  cancel: UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod4;
  close: UniffiCallbackInterfaceCuaDriverSdkForeignDriverEnvelopeChannelMethod5;
};
