// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

import lib from "@ubjs/node";
const { UniffiNativeModule, FfiType, resolveLibPath } = lib;

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from '@ubjs/core';

const DEFINITIONS = {
  symbols: {
    rustbuffer_alloc: "ffi_cyclops_sdk_rustbuffer_alloc",
    rustbuffer_free: "ffi_cyclops_sdk_rustbuffer_free",
    rustbuffer_from_bytes: "ffi_cyclops_sdk_rustbuffer_from_bytes",
  },
  functions: {
    "ffi_cyclops_sdk_rust_future_poll_u8": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_u8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_u8": {
      args: [FfiType.Handle],
      ret: FfiType.UInt8,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_u8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_i8": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_u16": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_u16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_u16": {
      args: [FfiType.Handle],
      ret: FfiType.UInt16,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_u16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_i16": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Int16,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_u32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_u32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_u32": {
      args: [FfiType.Handle],
      ret: FfiType.UInt32,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_u32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_i32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Int32,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_u64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_i64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Int64,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_f32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Float32,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_f64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Float64,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_rust_buffer": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_poll_void": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_cancel_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_cyclops_sdk_rust_future_complete_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_rust_future_free_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_clone_accesstokenprovider": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_accesstokenprovider": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_createclaimrequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_createclaimrequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_createpoolrequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_createpoolrequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_createsignedserviceurlrequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_createsignedserviceurlrequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_createtemplaterequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_createtemplaterequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_createuserapikeyrequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_createuserapikeyrequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_cyclopsclient": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_cyclopsclient": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_cyclopscredentials": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_cyclopscredentials": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_cyclopstokenproviderconfigurationbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_cyclopstokenproviderconfigurationbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_httpclient": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_httpclient": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_httprequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_httprequestbuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_clone_templatebuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_free_templatebuilder": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_init_callback_vtable_accesstokenprovider": {
      args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceFleetSdkAccessTokenProvider"))],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_init_callback_vtable_httpclient": {
      args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceFleetSdkHttpClient"))],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_func_fleet_label_key": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_func_healthy_pool_display_status": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_func_pool_display_status": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_func_removed_pool_display_status": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_func_terminating_pool_display_status": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_func_unknown_pool_display_status": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_accesstokenprovider_get_access_token": {
      args: [FfiType.Handle, FfiType.Int8],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_constructor_createclaimrequestbuilder_new": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_build": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_labels": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_name": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_pool": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_spec": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_createpoolrequestbuilder_new": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createpoolrequestbuilder_build": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createpoolrequestbuilder_namespace": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createpoolrequestbuilder_spec": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_createsignedserviceurlrequestbuilder_new": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_build": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_expires_in_seconds": {
      args: [FfiType.Handle, FfiType.UInt32],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_label": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_sandbox": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_service": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_createtemplaterequestbuilder_new": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createtemplaterequestbuilder_build": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createtemplaterequestbuilder_name": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createtemplaterequestbuilder_namespace": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createtemplaterequestbuilder_spec": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_createuserapikeyrequestbuilder_new": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createuserapikeyrequestbuilder_build": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createuserapikeyrequestbuilder_name": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_createuserapikeyrequestbuilder_scope": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect": {
      args: [FfiType.RustBuffer, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_browser_with_access_token": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_access_token": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_access_token_and_native_http_client": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_access_token_provider": {
      args: [FfiType.RustBuffer, FfiType.Handle, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_access_token_provider_and_native_http_client": {
      args: [FfiType.RustBuffer, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_native_http_client": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_access_token": {
      args: [FfiType.Handle, FfiType.Int8],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_create_claim": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_create_fleet_claims": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_create_image": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_create_namespace": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_create_pool": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_create_signed_service_url": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_create_template": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_create_user_api_key": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_claim": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_image": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_namespace": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_pool": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_template": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_user_api_key": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_get_claim": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_get_image": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_get_namespace": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_get_pool": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_get_template": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_list_claims": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_list_fleet_claims": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_list_images": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_list_namespaces": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_list_pools": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_list_signed_service_urls": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_list_templates": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_list_user_api_keys": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_presign_image_uploads": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_reconcile_pool": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_reconcile_template": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_renew_claim": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_revoke_signed_service_url": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_service_request": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_service_websocket_url": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_update_pool": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_update_template": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_upload_image_file": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopsclient_wait_claim": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopscredentials_new": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_cyclopstokenproviderconfigurationbuilder_new": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_base_url": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_build": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_claim_poll_interval_ms": {
      args: [FfiType.Handle, FfiType.UInt64],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_claim_poll_limit": {
      args: [FfiType.Handle, FfiType.UInt32],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_pool_poll_interval_ms": {
      args: [FfiType.Handle, FfiType.UInt64],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_pool_poll_limit": {
      args: [FfiType.Handle, FfiType.UInt32],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_httpclient_execute": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_fn_constructor_httprequestbuilder_new": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_httprequestbuilder_body": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_httprequestbuilder_build": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_httprequestbuilder_headers": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_httprequestbuilder_max_response_bytes": {
      args: [FfiType.Handle, FfiType.UInt64],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_httprequestbuilder_method": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_httprequestbuilder_timeout_secs": {
      args: [FfiType.Handle, FfiType.UInt64],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_httprequestbuilder_url": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_constructor_templatebuilder_new": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_templatebuilder_api_version": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_templatebuilder_build": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_templatebuilder_kind": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_templatebuilder_metadata": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_cyclops_sdk_fn_method_templatebuilder_spec": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "ffi_cyclops_sdk_uniffi_contract_version": {
      args: [],
      ret: FfiType.UInt32,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_func_fleet_label_key": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_func_healthy_pool_display_status": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_func_pool_display_status": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_func_removed_pool_display_status": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_func_terminating_pool_display_status": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_func_unknown_pool_display_status": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_accesstokenprovider_get_access_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_createclaimrequestbuilder_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_build": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_labels": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_name": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_pool": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_spec": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_createpoolrequestbuilder_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createpoolrequestbuilder_build": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createpoolrequestbuilder_namespace": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createpoolrequestbuilder_spec": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_createsignedserviceurlrequestbuilder_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_build": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_expires_in_seconds": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_label": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_sandbox": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_service": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_createtemplaterequestbuilder_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createtemplaterequestbuilder_build": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createtemplaterequestbuilder_name": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createtemplaterequestbuilder_namespace": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createtemplaterequestbuilder_spec": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_createuserapikeyrequestbuilder_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createuserapikeyrequestbuilder_build": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createuserapikeyrequestbuilder_name": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_createuserapikeyrequestbuilder_scope": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_browser_with_access_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_access_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_access_token_and_native_http_client": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_access_token_provider": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_access_token_provider_and_native_http_client": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_native_http_client": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_access_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_claim": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_fleet_claims": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_image": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_namespace": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_pool": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_signed_service_url": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_template": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_user_api_key": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_claim": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_image": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_namespace": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_pool": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_template": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_user_api_key": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_claim": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_image": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_namespace": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_pool": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_template": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_claims": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_fleet_claims": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_images": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_namespaces": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_pools": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_signed_service_urls": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_templates": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_user_api_keys": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_presign_image_uploads": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_reconcile_pool": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_reconcile_template": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_renew_claim": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_revoke_signed_service_url": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_service_request": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_service_websocket_url": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_update_pool": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_update_template": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_upload_image_file": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopsclient_wait_claim": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopscredentials_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_cyclopstokenproviderconfigurationbuilder_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_base_url": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_build": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_claim_poll_interval_ms": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_claim_poll_limit": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_pool_poll_interval_ms": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_pool_poll_limit": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_httpclient_execute": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_httprequestbuilder_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_httprequestbuilder_body": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_httprequestbuilder_build": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_httprequestbuilder_headers": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_httprequestbuilder_max_response_bytes": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_httprequestbuilder_method": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_httprequestbuilder_timeout_secs": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_httprequestbuilder_url": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_constructor_templatebuilder_new": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_templatebuilder_api_version": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_templatebuilder_build": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_templatebuilder_kind": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_templatebuilder_metadata": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_cyclops_sdk_checksum_method_templatebuilder_spec": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
  },
  callbacks: {
    "RustFutureContinuationCallback": {
      args: [FfiType.Handle, FfiType.Int8],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ForeignFutureDroppedCallback": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ForeignFutureCompleterust_buffer": {
      args: [FfiType.Handle, FfiType.Struct("ForeignFutureResultRustBuffer")],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFleetSdkAccessTokenProviderMethod0": {
      args: [FfiType.Handle, FfiType.Int8, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceCloneFleetSdk_AccessTokenProvider": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFreeFleetSdk_AccessTokenProvider": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFleetSdkHttpClientMethod0": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceCloneFleetSdk_HttpClient": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFreeFleetSdk_HttpClient": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
  },
  structs: {
    "ForeignFutureDroppedCallbackStruct": [
      { name: "handle", type: FfiType.Handle },
      { name: "free", type: FfiType.Callback("ForeignFutureDroppedCallback") },
    ],
    "ForeignFutureResultRustBuffer": [
      { name: "return_value", type: FfiType.RustBuffer },
      { name: "call_status", type: FfiType.RustCallStatus },
    ],
    "VTableCallbackInterfaceFleetSdkAccessTokenProvider": [
      { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeFleetSdk_AccessTokenProvider") },
      { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneFleetSdk_AccessTokenProvider") },
      { name: "get_access_token", type: FfiType.Callback("CallbackInterfaceFleetSdkAccessTokenProviderMethod0") },
    ],
    "VTableCallbackInterfaceFleetSdkHttpClient": [
      { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeFleetSdk_HttpClient") },
      { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneFleetSdk_HttpClient") },
      { name: "execute", type: FfiType.Callback("CallbackInterfaceFleetSdkHttpClientMethod0") },
    ],
  },
} as const;

interface NativeModuleInterface {
    ffi_cyclops_sdk_rust_future_poll_u8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_u8(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_u8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cyclops_sdk_rust_future_free_u8(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_i8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_i8(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_i8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cyclops_sdk_rust_future_free_i8(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_u16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_u16(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_u16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cyclops_sdk_rust_future_free_u16(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_i16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_i16(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_i16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cyclops_sdk_rust_future_free_i16(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_u32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_u32(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_u32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cyclops_sdk_rust_future_free_u32(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_i32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_i32(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_i32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cyclops_sdk_rust_future_free_i32(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_u64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_u64(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_u64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cyclops_sdk_rust_future_free_u64(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_i64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_i64(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_i64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cyclops_sdk_rust_future_free_i64(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_f32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_f32(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_f32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cyclops_sdk_rust_future_free_f32(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_f64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_f64(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_f64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cyclops_sdk_rust_future_free_f64(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_rust_buffer(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_rust_buffer(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_rust_buffer(handle: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ffi_cyclops_sdk_rust_future_free_rust_buffer(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_poll_void(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cyclops_sdk_rust_future_cancel_void(handle: bigint): void;
    ffi_cyclops_sdk_rust_future_complete_void(handle: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    ffi_cyclops_sdk_rust_future_free_void(handle: bigint): void;
    uniffi_cyclops_sdk_fn_clone_accesstokenprovider(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_accesstokenprovider(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_createclaimrequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_createclaimrequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_createpoolrequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_createpoolrequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_createsignedserviceurlrequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_createsignedserviceurlrequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_createtemplaterequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_createtemplaterequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_createuserapikeyrequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_createuserapikeyrequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_cyclopsclient(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_cyclopsclient(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_cyclopscredentials(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_cyclopscredentials(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_cyclopstokenproviderconfigurationbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_cyclopstokenproviderconfigurationbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_httpclient(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_httpclient(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_httprequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_httprequestbuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_clone_templatebuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_free_templatebuilder(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cyclops_sdk_fn_init_callback_vtable_accesstokenprovider(vtable: UniffiVTableCallbackInterfaceFleetSdkAccessTokenProvider): void;
    uniffi_cyclops_sdk_fn_init_callback_vtable_httpclient(vtable: UniffiVTableCallbackInterfaceFleetSdkHttpClient): void;
    uniffi_cyclops_sdk_fn_func_fleet_label_key(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_func_healthy_pool_display_status(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_func_pool_display_status(pool: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_func_removed_pool_display_status(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_func_terminating_pool_display_status(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_func_unknown_pool_display_status(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_accesstokenprovider_get_access_token(uniffiSelf: bigint, forceRefresh: number): bigint;
    uniffi_cyclops_sdk_fn_constructor_createclaimrequestbuilder_new(uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_build(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_labels(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_name(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_pool(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createclaimrequestbuilder_spec(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_createpoolrequestbuilder_new(uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createpoolrequestbuilder_build(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_createpoolrequestbuilder_namespace(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createpoolrequestbuilder_spec(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_createsignedserviceurlrequestbuilder_new(uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_build(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_expires_in_seconds(uniffiSelf: bigint, value: number, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_label(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_sandbox(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createsignedserviceurlrequestbuilder_service(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_createtemplaterequestbuilder_new(uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createtemplaterequestbuilder_build(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_createtemplaterequestbuilder_name(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createtemplaterequestbuilder_namespace(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createtemplaterequestbuilder_spec(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_createuserapikeyrequestbuilder_new(uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createuserapikeyrequestbuilder_build(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_createuserapikeyrequestbuilder_name(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_createuserapikeyrequestbuilder_scope(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect(configuration: Uint8Array, httpClient: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_browser_with_access_token(configuration: Uint8Array, accessToken: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_access_token(configuration: Uint8Array, accessToken: Uint8Array, httpClient: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_access_token_and_native_http_client(configuration: Uint8Array, accessToken: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_access_token_provider(configuration: Uint8Array, tokenProvider: bigint, httpClient: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_access_token_provider_and_native_http_client(configuration: Uint8Array, tokenProvider: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopsclient_connect_with_native_http_client(configuration: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_access_token(uniffiSelf: bigint, forceRefresh: number): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_create_claim(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_create_fleet_claims(uniffiSelf: bigint, fleetId: Uint8Array, requests: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_create_image(uniffiSelf: bigint, namespace: Uint8Array, manifest: bigint): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_create_namespace(uniffiSelf: bigint, name: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_create_pool(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_create_signed_service_url(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_create_template(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_create_user_api_key(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_claim(uniffiSelf: bigint, claim: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_image(uniffiSelf: bigint, namespace: Uint8Array, name: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_namespace(uniffiSelf: bigint, name: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_pool(uniffiSelf: bigint, pool: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_template(uniffiSelf: bigint, template: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_delete_user_api_key(uniffiSelf: bigint, id: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_get_claim(uniffiSelf: bigint, claim: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_get_image(uniffiSelf: bigint, namespace: Uint8Array, name: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_get_namespace(uniffiSelf: bigint, name: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_get_pool(uniffiSelf: bigint, name: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_get_template(uniffiSelf: bigint, namespace: Uint8Array, name: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_list_claims(uniffiSelf: bigint, namespace: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_list_fleet_claims(uniffiSelf: bigint, namespace: Uint8Array, fleetId: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_list_images(uniffiSelf: bigint, namespace: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_list_namespaces(uniffiSelf: bigint): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_list_pools(uniffiSelf: bigint, namespace: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_list_signed_service_urls(uniffiSelf: bigint, sandbox: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_list_templates(uniffiSelf: bigint, namespace: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_list_user_api_keys(uniffiSelf: bigint): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_presign_image_uploads(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_reconcile_pool(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_reconcile_template(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_renew_claim(uniffiSelf: bigint, claim: Uint8Array, shutdownTime: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_revoke_signed_service_url(uniffiSelf: bigint, signedServiceUrl: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_service_request(uniffiSelf: bigint, sandbox: Uint8Array, service: Uint8Array, path: Uint8Array, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_service_websocket_url(uniffiSelf: bigint, sandbox: Uint8Array, service: Uint8Array, path: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_update_pool(uniffiSelf: bigint, pool: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_update_template(uniffiSelf: bigint, template: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_upload_image_file(uniffiSelf: bigint, namespace: Uint8Array, name: Uint8Array, contents: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopsclient_wait_claim(uniffiSelf: bigint, claim: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopscredentials_new(clientId: Uint8Array, clientSecret: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_cyclopstokenproviderconfigurationbuilder_new(uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_base_url(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_build(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_claim_poll_interval_ms(uniffiSelf: bigint, value: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_claim_poll_limit(uniffiSelf: bigint, value: number, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_pool_poll_interval_ms(uniffiSelf: bigint, value: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_cyclopstokenproviderconfigurationbuilder_pool_poll_limit(uniffiSelf: bigint, value: number, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_httpclient_execute(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cyclops_sdk_fn_constructor_httprequestbuilder_new(uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_httprequestbuilder_body(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_httprequestbuilder_build(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_httprequestbuilder_headers(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_httprequestbuilder_max_response_bytes(uniffiSelf: bigint, value: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_httprequestbuilder_method(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_httprequestbuilder_timeout_secs(uniffiSelf: bigint, value: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_httprequestbuilder_url(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_constructor_templatebuilder_new(uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_templatebuilder_api_version(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_templatebuilder_build(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cyclops_sdk_fn_method_templatebuilder_kind(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_templatebuilder_metadata(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cyclops_sdk_fn_method_templatebuilder_spec(uniffiSelf: bigint, value: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cyclops_sdk_uniffi_contract_version(): number;
    uniffi_cyclops_sdk_checksum_func_fleet_label_key(): number;
    uniffi_cyclops_sdk_checksum_func_healthy_pool_display_status(): number;
    uniffi_cyclops_sdk_checksum_func_pool_display_status(): number;
    uniffi_cyclops_sdk_checksum_func_removed_pool_display_status(): number;
    uniffi_cyclops_sdk_checksum_func_terminating_pool_display_status(): number;
    uniffi_cyclops_sdk_checksum_func_unknown_pool_display_status(): number;
    uniffi_cyclops_sdk_checksum_method_accesstokenprovider_get_access_token(): number;
    uniffi_cyclops_sdk_checksum_constructor_createclaimrequestbuilder_new(): number;
    uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_build(): number;
    uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_labels(): number;
    uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_name(): number;
    uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_pool(): number;
    uniffi_cyclops_sdk_checksum_method_createclaimrequestbuilder_spec(): number;
    uniffi_cyclops_sdk_checksum_constructor_createpoolrequestbuilder_new(): number;
    uniffi_cyclops_sdk_checksum_method_createpoolrequestbuilder_build(): number;
    uniffi_cyclops_sdk_checksum_method_createpoolrequestbuilder_namespace(): number;
    uniffi_cyclops_sdk_checksum_method_createpoolrequestbuilder_spec(): number;
    uniffi_cyclops_sdk_checksum_constructor_createsignedserviceurlrequestbuilder_new(): number;
    uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_build(): number;
    uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_expires_in_seconds(): number;
    uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_label(): number;
    uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_sandbox(): number;
    uniffi_cyclops_sdk_checksum_method_createsignedserviceurlrequestbuilder_service(): number;
    uniffi_cyclops_sdk_checksum_constructor_createtemplaterequestbuilder_new(): number;
    uniffi_cyclops_sdk_checksum_method_createtemplaterequestbuilder_build(): number;
    uniffi_cyclops_sdk_checksum_method_createtemplaterequestbuilder_name(): number;
    uniffi_cyclops_sdk_checksum_method_createtemplaterequestbuilder_namespace(): number;
    uniffi_cyclops_sdk_checksum_method_createtemplaterequestbuilder_spec(): number;
    uniffi_cyclops_sdk_checksum_constructor_createuserapikeyrequestbuilder_new(): number;
    uniffi_cyclops_sdk_checksum_method_createuserapikeyrequestbuilder_build(): number;
    uniffi_cyclops_sdk_checksum_method_createuserapikeyrequestbuilder_name(): number;
    uniffi_cyclops_sdk_checksum_method_createuserapikeyrequestbuilder_scope(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_browser_with_access_token(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_access_token(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_access_token_and_native_http_client(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_access_token_provider(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_access_token_provider_and_native_http_client(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopsclient_connect_with_native_http_client(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_access_token(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_claim(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_fleet_claims(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_image(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_namespace(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_pool(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_signed_service_url(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_template(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_create_user_api_key(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_claim(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_image(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_namespace(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_pool(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_template(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_delete_user_api_key(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_claim(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_image(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_namespace(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_pool(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_get_template(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_claims(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_fleet_claims(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_images(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_namespaces(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_pools(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_signed_service_urls(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_templates(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_list_user_api_keys(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_presign_image_uploads(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_reconcile_pool(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_reconcile_template(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_renew_claim(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_revoke_signed_service_url(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_service_request(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_service_websocket_url(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_update_pool(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_update_template(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_upload_image_file(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopsclient_wait_claim(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopscredentials_new(): number;
    uniffi_cyclops_sdk_checksum_constructor_cyclopstokenproviderconfigurationbuilder_new(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_base_url(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_build(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_claim_poll_interval_ms(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_claim_poll_limit(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_pool_poll_interval_ms(): number;
    uniffi_cyclops_sdk_checksum_method_cyclopstokenproviderconfigurationbuilder_pool_poll_limit(): number;
    uniffi_cyclops_sdk_checksum_method_httpclient_execute(): number;
    uniffi_cyclops_sdk_checksum_constructor_httprequestbuilder_new(): number;
    uniffi_cyclops_sdk_checksum_method_httprequestbuilder_body(): number;
    uniffi_cyclops_sdk_checksum_method_httprequestbuilder_build(): number;
    uniffi_cyclops_sdk_checksum_method_httprequestbuilder_headers(): number;
    uniffi_cyclops_sdk_checksum_method_httprequestbuilder_max_response_bytes(): number;
    uniffi_cyclops_sdk_checksum_method_httprequestbuilder_method(): number;
    uniffi_cyclops_sdk_checksum_method_httprequestbuilder_timeout_secs(): number;
    uniffi_cyclops_sdk_checksum_method_httprequestbuilder_url(): number;
    uniffi_cyclops_sdk_checksum_constructor_templatebuilder_new(): number;
    uniffi_cyclops_sdk_checksum_method_templatebuilder_api_version(): number;
    uniffi_cyclops_sdk_checksum_method_templatebuilder_build(): number;
    uniffi_cyclops_sdk_checksum_method_templatebuilder_kind(): number;
    uniffi_cyclops_sdk_checksum_method_templatebuilder_metadata(): number;
    uniffi_cyclops_sdk_checksum_method_templatebuilder_spec(): number;
    // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
    // and `nativeModule().rustbuffer_free(...)`. The runtime's registered
    // module exposes them as method properties.
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}

let _nativeModule: NativeModuleInterface | undefined;
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    const libPath = resolveLibPath({
      crateName: "cyclops_sdk",
      callerUrl: import.meta.url,
    });
    const mod_ = UniffiNativeModule.open(libPath);
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface;
  }
  return _nativeModule;
};
export default getter;

// Structs and function types for calling back into Typescript from Rust.
export type UniffiRustFutureContinuationCallback = (data: bigint, pollResult: number) => void;
export type UniffiForeignFutureDroppedCallback = (handle: bigint) => void;
export type UniffiForeignFutureDroppedCallbackStruct = {
  handle: bigint;
  free: UniffiForeignFutureDroppedCallback;
};
export type UniffiForeignFutureResultRustBuffer = {
  return_value: Uint8Array;
  call_status: UniffiRustCallStatus;
};
export type UniffiForeignFutureCompleterustBuffer = (callbackData: bigint, result: UniffiForeignFutureResultRustBuffer) => void;
type UniffiCallbackInterfaceFleetSdkAccessTokenProviderMethod0 = (uniffiHandle: bigint, forceRefresh: number, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCloneFleetSdkAccessTokenProvider = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeFleetSdkAccessTokenProvider = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceFleetSdkAccessTokenProvider = {
  uniffi_free: UniffiCallbackInterfaceFreeFleetSdkAccessTokenProvider;
  uniffi_clone: UniffiCallbackInterfaceCloneFleetSdkAccessTokenProvider;
  get_access_token: UniffiCallbackInterfaceFleetSdkAccessTokenProviderMethod0;
};
type UniffiCallbackInterfaceFleetSdkHttpClientMethod0 = (uniffiHandle: bigint, request: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCloneFleetSdkHttpClient = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeFleetSdkHttpClient = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceFleetSdkHttpClient = {
  uniffi_free: UniffiCallbackInterfaceFreeFleetSdkHttpClient;
  uniffi_clone: UniffiCallbackInterfaceCloneFleetSdkHttpClient;
  execute: UniffiCallbackInterfaceFleetSdkHttpClientMethod0;
};
