[package]
name = "cyclops-sdk"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
async-trait.workspace = true
base64.workspace = true
cyclops-sdk-schema = { path = "../sdk-schema" }
futures-timer.workspace = true
petname = { version = "2", default-features = false, features = [
    "default-rng",
    "default-words",
] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
uniffi.workspace = true
uniffi-builder-derive = { path = "../uniffi-builder-derive" }
url.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
gloo-timers = { version = "0.3", features = ["futures"] }
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-time = "1.1.0"
web-sys = { version = "0.3", features = ["AbortController", "AbortSignal", "Headers", "ReadableStream", "ReadableStreamDefaultReader", "Request", "RequestInit", "RequestRedirect", "RequestCredentials", "Response", "Window"] }

[dev-dependencies]
camino = "1.0"
tokio = { workspace = true, features = ["rt-multi-thread"] }
uniffi = { workspace = true, features = ["bindgen"] }
